### ISSUE TITLE
Area Export - Consistently Fails

### ISSUE THREAD

**Issue by MYRWYR** [JonathanCRH/Undiscovered_Worlds#10]
So far, if the area is too large (warning), UW crashes as expected - but when an area is small enough to not raise the warning and I export, after a few moments UW returns to the world view without exporting to the expected folder. I have not been able to confirm whether or not it is exported elsewhere by mistake.

This has been reproduced consecutively without variation - I have not managed a successful export for any region, not even when selecting a single area (not several areas by dragging).

**Comment by MYRWYR** [comment]
Closed - I just realised this was the "new" UW, not "Classic".

**Comment by islammutiev** [comment]
I have the same problem, but a little bit different. I've been able to succesfully export areaa that do not trigger a crashing warning, but have that problem with areas that trigger said warnings - that is, if they don't crash. So bigger areas either crash or act like they had been exported and are nowhere to be found.

**Comment by MYRWYR** [comment]
The issue seems to be related to memory management, or limits. I doubled my system RAM and was able to export significantly larger areas.
